"""
Train a statistical ML model that makes PRIMARY decisions.
Uses TF-IDF n-grams + statistical features + Gradient Boosting.
"""

import pickle
import sys
import re
import math
from pathlib import Path
from collections import Counter
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline, FeatureUnion

# Import the shared feature extractor class
sys.path.insert(0, str(Path(__file__).parent))
from feature_extractor import StatisticalFeatureExtractor

TESTS_DIR = Path(__file__).parent
MODEL_DIR = TESTS_DIR / "model"
MODEL_DIR.mkdir(exist_ok=True)

# =====================================================================
# LABELED TRAINING DATA - 480 SCAMS + 273 LEGIT = 753 TOTAL
# =====================================================================

SCAM_TEXTS = [
    # KYC Scams (40)
    "Dear customer, your KYC is pending. Update now to avoid account closure. Click: hdfc-kyc-update.com/verify",
    "Your SBI account will be blocked today. Update PAN details: sbi-pan-update.in/urgent",
    "ICICI Bank: Your KYC has expired. Update immediately: icici-kyc-verify.com",
    "ALERT: KYC update required within 24 hours. Verify: kyc-update-urgent.in",
    "Your KYC verification failed. Complete now: bank-kyc-verify.net/complete",
    "RBI mandate: Update KYC by today. Click: rbi-kyc-mandate.com/update",
    "Your account KYC is incomplete. Update PAN: pan-kyc-update.xyz",
    "KYC reminder: Update before account freeze. Verify: kyc-reminder.in",
    "Your KYC documents rejected. Resubmit: kyc-resubmit.cc/upload",
    "Final KYC notice: Account will be suspended. Update: final-kyc-notice.com",
    "HDFC: KYC pending for 30 days. Update or account blocked: hdfc-kyc-30days.in",
    "SBI: KYC deadline today. Update now: sbi-kyc-deadline.xyz",
    "ICICI: Your KYC status is inactive. Activate: icici-kyc-inactive.cc",
    "Axis Bank: KYC verification pending. Verify: axis-kyc-pending.in",
    "Paytm: KYC mandatory. Complete now: paytm-kyc-mandatory.xyz",
    "PhonePe: KYC incomplete. Update: phonepe-kyc-incomplete.in",
    "Amazon Pay: KYC required. Verify: amazonpay-kyc.xyz",
    "Google Pay: KYC pending. Update: gpay-kyc-pending.in",
    "Your bank account KYC expired. Renew: bank-kyc-expired.cc",
    "KYC update mandatory by RBI. Update: rbi-kyc-mandatory.in",
    "KYC suspension notice. Reactivate: kyc-suspension.xyz",
    "Your KYC is under review. Verify: kyc-review.in",
    "KYC verification timeout. Resubmit: kyc-timeout.cc",
    "Bank KYC compliance required. Update: bank-compliance.in",
    "KYC non-compliance alert. Update: kyc-noncompliance.xyz",
    "Your KYC profile incomplete. Complete: kyc-profile.in",
    "KYC update overdue. Update now: kyc-overdue.cc",
    "RBI KYC guidelines. Update: rbi-guidelines.in",
    "KYC mandatory for all accounts. Update: kyc-all-accounts.xyz",
    "Your KYC will expire soon. Renew: kyc-expire-soon.in",
    "KYC update reminder. Update: kyc-reminder-2.xyz",
    "Bank KYC policy change. Update: bank-policy.in",
    "KYC verification pending for 60 days. Update: kyc-60days.cc",
    "Your KYC is invalid. Re-verify: kyc-invalid.in",
    "KYC update required for UPI. Update: kyc-upi.xyz",
    "Bank KYC audit. Update required: kyc-audit.in",
    "KYC compliance deadline. Update: kyc-deadline-2.cc",
    "Your KYC needs updating. Update: kyc-needs-update.in",
    "KYC verification error. Resubmit: kyc-error.xyz",
    "Bank KYC system update. Re-verify: kyc-system.in",
    
    # Banking/Phishing (40)
    "ALERT: Suspicious transaction of Rs.25,000 detected. Verify immediately: sbi-secure-login.net/check",
    "ICICI Bank: Your account is locked. Verify identity: icici-verify.com/login",
    "Your HDFC credit card statement is ready. View: hdfc-statement-view.com/login",
    "Axis Bank: OTP is 847291. Never share. Verify: axis-otp-verify.net",
    "Bank Alert: Login from new device. Verify: hdfc-secure.net/verify",
    "Account suspended. Reactivate: icici-reactivate.com/login",
    "Transaction failed. Update details: sbi-update.net/verify",
    "Card blocked. Verify now: hdfc-card-verify.com",
    "Account locked. Unlock: axis-unlock.net",
    "Account alert. Verify: bank-verify.in",
    "Your SBI netbanking password expired. Reset: sbi-password-reset.com",
    "HDFC: Unauthorized transaction detected. Dispute: hdfc-dispute.net",
    "ICICI: Your card will expire tomorrow. Renew: icici-card-renew.xyz",
    "Axis: Login attempt from new device. Confirm: axis-confirm-login.com",
    "Federal Bank: Your account access restricted. Verify: federal-verify-access.in",
    "Bank account frozen. Unfreeze: bank-frozen.cc",
    "Your card has been blocked. Unblock: card-blocked.in",
    "Suspicious activity detected. Verify: suspicious-activity.xyz",
    "Your account is compromised. Secure: account-compromised.in",
    "Bank security alert. Verify: bank-security.cc",
    "Your netbanking is blocked. Unblock: netbanking-blocked.in",
    "Card transaction declined. Update: card-declined.xyz",
    "Your account needs verification. Verify: account-verify-2.in",
    "Bank fraud alert. Verify: bank-fraud.cc",
    "Your card is expired. Renew: card-expired-2.in",
    "Account verification required. Verify: account-verify-3.xyz",
    "Your netbanking session expired. Login: netbanking-expired.in",
    "Bank password reset required. Reset: bank-password.cc",
    "Your card is suspended. Reactivate: card-suspended.in",
    "Account security update. Update: account-security.xyz",
    "Your netbanking is locked. Unlock: netbanking-locked.in",
    "Bank OTP verification. Verify: bank-otp-2.cc",
    "Your card limit exceeded. Update: card-limit.in",
    "Account activity alert. Verify: account-activity.xyz",
    "Your netbanking needs update. Update: netbanking-update.in",
    "Bank login alert. Verify: bank-login.cc",
    "Your card PIN blocked. Reset: card-pin.in",
    "Account access denied. Verify: account-denied.xyz",
    "Your netbanking credentials expired. Update: netbanking-creds.in",
    "Bank transaction alert. Verify: bank-transaction.cc",
    
    # Courier/Customs (30)
    "Customs Department: Your package is held. Pay duty Rs.500: customs-duty.cc/pay",
    "Courier: Package stuck at customs. Pay Rs.750: fedex-customs.cc/pay",
    "Your parcel from USA is held at Delhi customs. Pay duty: customs-hold.in/pay",
    "DHL: Import duty pending for your package. Pay Rs.1,200: dhl-duty.cc",
    "BlueDart: Your shipment requires customs clearance. Pay: bluedart-customs.net",
    "India Post: International package held. Pay customs fee: indiapost-customs.xyz",
    "Your courier package is stuck. Clear customs: courier-stuck.cc/clear",
    "Customs notice: Pay import duty for your parcel. Click: customs-notice.in/pay",
    "FedEx: Your package delivery failed. Reschedule: fedex-reschedule.cc",
    "DTDC: Package held at sorting facility. Pay clearance fee: dtdc-clear.xyz",
    "Your package is awaiting customs clearance. Pay: package-clearance.in",
    "Courier delivery on hold. Pay duty: courier-hold.cc",
    "Customs inspection required. Pay fee: customs-inspection.in",
    "Your shipment is delayed. Pay customs: shipment-delayed.xyz",
    "Package stuck in transit. Clear: package-stuck.in",
    "Import duty payment pending. Pay: import-duty-2.cc",
    "Your parcel requires payment. Pay: parcel-payment.in",
    "Courier customs charge. Pay: courier-charge.xyz",
    "Package held for inspection. Pay: package-inspection.in",
    "Customs clearance fee due. Pay: clearance-fee.cc",
    "Your delivery is on hold. Pay: delivery-hold.in",
    "Shipment customs pending. Pay: shipment-customs.xyz",
    "Package delivery failed. Pay duty: delivery-failed.in",
    "Courier payment required. Pay: courier-payment.cc",
    "Your parcel is detained. Pay: parcel-detained.in",
    "Customs duty overdue. Pay: customs-overdue.xyz",
    "Package clearance required. Pay: clearance-required.in",
    "Your shipment needs payment. Pay: shipment-payment.cc",
    "Courier fee pending. Pay: courier-fee.in",
    "Package inspection fee. Pay: inspection-fee.xyz",
    
    # Reward/Cashback (30)
    "Congratulations! You won Rs.50,000 cashback. Claim now: paytm-reward.xyz/claim",
    "PhonePe: Rs.2,000 cashback credited. Scan to withdraw: phonepe-cashback.xyz",
    "Amazon Pay: Rs.500 reward. Click to claim: amazon-reward.xyz/claim",
    "Flipkart: You've won a gift card worth Rs.5,000. Claim: flipkart-gift.xyz",
    "Google Pay: Cashback of Rs.1,000 pending. Claim now: gpay-cashback.cc",
    "Payment of Rs.15,000 received. Scan QR to confirm: [UPI_QR_CODE]",
    "Your account credited Rs.45,000. Scan QR to pay: [MALICIOUS_QR]",
    "Cashback earned Rs.1,000. Scan to claim: [QR_CODE]",
    "Refund pending Rs.5,000. Claim: refund-claim.cc",
    "Payment received Rs.30,000. Confirm: [QR]",
    "You've won a lucky draw prize of Rs.25,000. Claim: lucky-draw-win.in",
    "Mega cashback offer! Rs.10,000. Claim: mega-cashback.xyz",
    "Your reward points: 50,000. Redeem: reward-points.in",
    "Congratulations on winning! Rs.75,000. Claim: congrats-win.cc",
    "Cashback pending approval. Approve: cashback-approval.in",
    "Your cashback is ready. Claim: cashback-ready.xyz",
    "Reward redemption pending. Redeem: reward-redemption.in",
    "You won a surprise gift! Claim: surprise-gift.cc",
    "Cashback credited to wallet. Withdraw: cashback-wallet.in",
    "Your reward is waiting. Claim: reward-waiting.xyz",
    "Prize money pending. Claim: prize-money.in",
    "Cashback offer expires today. Claim: cashback-expires.cc",
    "Your lottery winnings. Claim: lottery-winnings.in",
    "Reward points expiring. Redeem: points-expiring.xyz",
    "Cashback verification required. Verify: cashback-verify.in",
    "Your gift card is ready. Claim: gift-card-ready.cc",
    "Prize claim pending. Claim: prize-claim.in",
    "Cashback pending transfer. Transfer: cashback-transfer.xyz",
    "Your reward balance. Claim: reward-balance.in",
    "Winning amount pending. Claim: winning-amount.cc",
    
    # Government (30)
    "Income Tax: Refund of Rs.12,500 pending. Claim: incometax-refund.cc/claim",
    "EPFO: Your PF withdrawal approved. Verify: epfo-claim.in/verify",
    "Your PAN is not linked. Update now: pan-link-update.com/urgent",
    "PAN update required. Click: pan-update.xyz",
    "Income Tax Department: File ITR now to avoid penalty. File: itr-file-now.cc",
    "EPFO: Your UAN is not verified. Verify: uan-verify-epfo.in",
    "Government subsidy pending. Claim now: govt-subsidy-claim.xyz",
    "Aadhaar verification failed. Update: aadhaar-verify-urgent.in",
    "Ration card update required. Click: ration-card-update.cc",
    "Voter ID verification pending. Verify: voter-id-verify.xyz",
    "Income Tax refund approved. Claim: tax-refund-approved.in",
    "EPFO pension update. Update: epfo-pension.cc",
    "Your PAN card expired. Renew: pan-expired.in",
    "Aadhaar linking mandatory. Link: aadhaar-link.xyz",
    "Government scheme benefit. Claim: govt-scheme.in",
    "Income Tax notice. Respond: tax-notice.cc",
    "EPFO balance update. Check: epfo-balance.in",
    "Your ration card expired. Renew: ration-expired.xyz",
    "Voter ID update required. Update: voter-update.in",
    "Government grant approved. Claim: govt-grant.cc",
    "Income Tax penalty notice. Pay: tax-penalty.in",
    "EPFO nomination update. Update: epfo-nomination.xyz",
    "Your Aadhaar is blocked. Unblock: aadhaar-blocked.in",
    "PAN verification pending. Verify: pan-verify.cc",
    "Government relief fund. Claim: relief-fund.in",
    "Income Tax assessment. Respond: tax-assessment.xyz",
    "EPFO withdrawal pending. Withdraw: epfo-withdrawal.in",
    "Your ration card blocked. Unblock: ration-blocked.cc",
    "Voter ID renewal. Renew: voter-renewal.in",
    "Government compensation. Claim: govt-compensation.xyz",
    
    # E-Challan (30)
    "Traffic Police: Your challan of Rs.2,000 is pending. Pay: e-challan-pay.cc",
    "Traffic fine: Rs.5,000 for signal jumping. Pay now: traffic-challan.in/pay",
    "Your vehicle challan is overdue. Pay immediately: vehicle-challan.cc",
    "RTO notice: Traffic violation fine pending. Pay: rto-fine-notice.xyz",
    "E-challan: Rs.1,500 fine for no helmet. Pay: e-challan-helmet.in",
    "Delhi Traffic Police: Challan for overspeeding. Pay Rs.3,000: delhi-challan.cc",
    "Mumbai Police: Traffic violation detected. Pay fine: mumbai-traffic.xyz",
    "Your driving license suspended due to pending challan. Pay: dl-suspended.in",
    "Vehicle RC renewal blocked. Clear challan: rc-renewal.cc/pay",
    "E-challan notice: Rs.2,500 for wrong parking. Pay: parking-challan.xyz",
    "Traffic violation alert. Pay fine: traffic-violation.in",
    "Your vehicle is fined. Pay: vehicle-fine.cc",
    "Challan payment overdue. Pay: challan-overdue.in",
    "RTO fine notice. Pay: rto-fine.xyz",
    "Traffic police notice. Pay: police-notice.in",
    "Your challan is pending. Pay: challan-pending.cc",
    "Driving license fine. Pay: dl-fine.in",
    "Vehicle penalty notice. Pay: vehicle-penalty.xyz",
    "E-challan reminder. Pay: challan-reminder.in",
    "Traffic fine overdue. Pay: fine-overdue.cc",
    "Your RC is blocked. Pay: rc-blocked.in",
    "Challan clearance required. Pay: challan-clearance.xyz",
    "RTO violation notice. Pay: rto-violation.in",
    "Traffic penalty pending. Pay: penalty-pending.cc",
    "Your DL is suspended. Pay: dl-suspended-2.in",
    "E-challan final notice. Pay: challan-final.xyz",
    "Vehicle fine pending. Pay: vehicle-fine-2.in",
    "Challan payment required. Pay: challan-required.cc",
    "Traffic violation fine. Pay: violation-fine.in",
    "RTO penalty notice. Pay: rto-penalty.xyz",
    
    # Utility (30)
    "Electricity board: Your bill overdue. Disconnection today. Pay: electricity-bill.cc",
    "Power cut notice: Pay outstanding bill immediately: power-cut-notice.in",
    "Your electricity connection will be disconnected. Pay now: electricity-disconnect.xyz",
    "Gas bill overdue: Pay Rs.3,500 to avoid disconnection: gas-bill-pay.cc",
    "Water bill pending: Pay immediately or connection cut: water-bill-urgent.in",
    "BSNL: Your telephone bill overdue. Pay Rs.2,000: bsnl-bill.cc",
    "MTNL: Broadband bill pending. Pay now: mtnl-broadbill.xyz",
    "Your prepaid mobile will be disconnected. Recharge: mobile-recharge-urgent.in",
    "DTH connection blocked. Pay outstanding: dth-blocked.cc/pay",
    "Pipeline gas connection suspended. Pay bill: gas-suspended.xyz",
    "Electricity disconnection warning. Pay: electricity-warning.in",
    "Your power will be cut. Pay: power-cut.cc",
    "Bill payment overdue. Pay: bill-overdue.in",
    "Utility bill pending. Pay: utility-pending.xyz",
    "Connection suspension notice. Pay: connection-suspend.in",
    "Your electricity is blocked. Pay: electricity-blocked.cc",
    "Gas connection blocked. Pay: gas-blocked.in",
    "Water connection suspended. Pay: water-suspended.xyz",
    "BSNL bill overdue. Pay: bsnl-overdue.in",
    "MTNL payment pending. Pay: mtnl-pending.cc",
    "Mobile disconnection notice. Pay: mobile-disconnect.in",
    "DTH bill overdue. Pay: dth-overdue.xyz",
    "Your utility bill is due. Pay: utility-due.in",
    "Electricity penalty notice. Pay: electricity-penalty.cc",
    "Gas bill pending. Pay: gas-pending.in",
    "Water bill overdue. Pay: water-overdue.xyz",
    "BSNL disconnection warning. Pay: bsnl-warning.in",
    "MTNL bill pending. Pay: mtnl-bill.cc",
    "Your connection is blocked. Pay: connection-blocked.in",
    "Utility payment overdue. Pay: utility-overdue.xyz",
    
    # Job (25)
    "Work from home opportunity! Earn Rs.50,000/month. Register: wfh-job.xyz",
    "Data entry job: Earn Rs.30,000 weekly. Apply now: dataentry-job.cc",
    "Part-time job: Rs.2,000 daily. No experience needed. Join: parttime-job.in",
    "Online typing job: Earn Rs.15,000/week. Apply: typing-job-urgent.xyz",
    "Amazon hiring: Work from home. Salary Rs.40,000. Apply: amazon-job-fake.cc",
    "Flipkart job opening: Earn Rs.35,000. Register: flipkart-job-scam.in",
    "Government job vacancy: Apply now. Fee Rs.500: govt-job-fake.xyz",
    "Bank job recruitment: Apply online. Pay fee: bank-job-scam.cc",
    "Telecalling job: Earn Rs.25,000/month. Join: telecall-job.xyz",
    "Freelance writing job: Rs.5,000 per article. Apply: writing-job-fake.in",
    "Remote job opportunity. Earn: remote-job.xyz",
    "Online job opening. Apply: online-job.cc",
    "Part-time work. Earn daily: parttime-work.in",
    "Home-based job. Salary: home-job.xyz",
    "Data entry work. Earn: dataentry-work.cc",
    "Typing job available. Apply: typing-job.in",
    "Customer service job. Earn: customer-job.xyz",
    "Sales job opening. Apply: sales-job.cc",
    "Marketing job. Earn: marketing-job.in",
    "Admin job available. Apply: admin-job.xyz",
    "HR job opening. Earn: hr-job.cc",
    "IT job available. Apply: it-job.in",
    "Finance job opening. Earn: finance-job.xyz",
    "Accounting job. Apply: accounting-job.cc",
    "Management job. Earn: management-job.in",
    
    # Lottery (25)
    "Lottery: You won Rs.1,00,000! Contact: +91-9876543210",
    "Congratulations! You won a lucky draw prize of Rs.25,000. Claim: lucky-draw-win.in",
    "You've won Rs.5,00,000 in our international lottery. Claim: intl-lottery.cc",
    "Dear winner, you've won Rs.10,00,000. Contact agent: lottery-agent.xyz",
    "Mega lottery winner! Prize Rs.50,00,000. Claim now: mega-lottery.in",
    "You are selected for Rs.2,00,000 prize. Verify: prize-verify.cc",
    "Lottery result: Your ticket won Rs.75,000. Claim: lottery-claim.xyz",
    "You won a car worth Rs.15,00,000! Pay tax to claim: car-lottery.in",
    "International lottery: You won $10,000. Claim: us-lottery-claim.cc",
    "Lucky winner! You won Rs.3,00,000. Contact: lottery-winner.xyz",
    "You won the jackpot! Claim: jackpot-win.in",
    "Prize winner notification. Claim: prize-winner.cc",
    "Lucky draw result. Claim: lucky-result.in",
    "Lottery prize pending. Claim: lottery-pending.xyz",
    "You are a winner! Claim: you-winner.in",
    "Prize money won. Claim: prize-won.cc",
    "Lottery ticket winner. Claim: ticket-winner.in",
    "Congratulations winner! Claim: congrats-winner.xyz",
    "Prize claim notice. Claim: prize-notice.in",
    "Lottery payout pending. Claim: lottery-payout.cc",
    "You won big! Claim: won-big.in",
    "Prize distribution. Claim: prize-distribution.xyz",
    "Lottery award. Claim: lottery-award.in",
    "Winner announcement. Claim: winner-announce.cc",
    "Prize collection. Claim: prize-collection.in",
    
    # Crypto/Investment (50)
    "Bitcoin investment: Earn 200% returns in 30 days. Invest now: crypto-rich.xyz",
    "Your crypto wallet compromised. Secure: wallet-secure-urgent.cc",
    "Crypto airdrop: Claim 5000 USDT free. Claim: airdrop-claim.in",
    "Your Bitcoin pending. Withdraw: btc-withdraw-now.xyz",
    "Crypto exchange: Your account locked. Verify: exchange-verify.cc",
    "NFT giveaway: Win 10 ETH. Claim: nft-giveaway.in",
    "Your crypto KYC expired. Update: crypto-kyc.xyz",
    "Crypto mining pool: Earn daily. Join: mining-pool.cc",
    "Your DeFi wallet suspended. Reactivate: defi-reactivate.in",
    "Crypto trading bot: 150% monthly returns. Invest: trading-bot.xyz",
    "Your Binance account restricted. Verify: binance-verify.cc",
    "Crypto staking rewards: Earn 50% APY. Stake: staking-rewards.in",
    "Your Ethereum transaction pending. Confirm: eth-confirm.xyz",
    "Crypto loan approved. Claim: crypto-loan.cc",
    "Your Coinbase account locked. Unlock: coinbase-unlock.in",
    "Crypto presale: 100x returns guaranteed. Invest: presale-100x.xyz",
    "Your USDT transfer failed. Retry: usdt-retry.cc",
    "Crypto VIP group: Insider signals. Join: vip-signals.in",
    "Your Metamask wallet compromised. Secure: metamask-secure.xyz",
    "Crypto arbitrage: Risk-free profits. Invest: arbitrage-profits.cc",
    "Your PancakeSwap liquidity locked. Unlock: pancakeswap-unlock.in",
    "Crypto insurance: Protect your assets. Buy: crypto-insurance.xyz",
    "Your Solana transaction stuck. Fix: solana-fix.cc",
    "Crypto referral: Earn 30% commission. Refer: referral-30percent.in",
    "Your Trust Wallet hacked. Recover: trust-recover.xyz",
    "Crypto futures: 1000x leverage. Trade: futures-1000x.cc",
    "Your Cardano staking rewards pending. Claim: cardano-rewards.in",
    "Crypto OTC desk: Buy/sell large amounts. Trade: otc-desk.xyz",
    "Your Polkadot DOT locked. Unlock: dot-unlock.cc",
    "Crypto yield farming: 500% APY. Farm: yield-500percent.in",
    "Your Avalanche AVAX pending. Withdraw: avax-withdraw.xyz",
    "Crypto hedge fund: Guaranteed returns. Invest: hedge-fund.cc",
    "Your Ripple XRP frozen. Unfreeze: xrp-unfreeze.in",
    "Crypto copy trading: Earn while you sleep. Copy: copy-trading.xyz",
    "Your Chainlink LINK rewards pending. Claim: link-rewards.cc",
    "Crypto liquidity mining: 1000% APY. Mine: liquidity-1000percent.in",
    "Your Uniswap position liquidated. Recover: uniswap-recover.xyz",
    "Crypto savings account: 20% interest. Save: crypto-savings.cc",
    "Your Polygon MATIC rewards pending. Claim: matic-rewards.in",
    "Crypto derivatives: Trade with confidence. Trade: derivatives-trade.xyz",
    "Your Dogecoin DOGE rewards pending. Claim: doge-rewards.cc",
    "Crypto index fund: Diversified portfolio. Invest: index-fund.in",
    "Your Shiba Inu SHIB rewards pending. Claim: shib-rewards.xyz",
    "Crypto robo-advisor: AI-powered trading. Invest: robo-advisor.cc",
    "Your Cosmos ATOM rewards pending. Claim: atom-rewards.in",
    "Crypto wealth management: Grow your portfolio. Manage: wealth-manage.xyz",
    "Your Terra LUNA rewards pending. Claim: luna-rewards.cc",
    "Crypto pension plan: Retire rich. Invest: crypto-pension.in",
    "Your Algorand ALGO rewards pending. Claim: algo-rewards.xyz",
    "Crypto retirement account: Tax-free gains. Invest: crypto-retirement.cc",
    
    # Tech Support (50)
    "Microsoft: Your Windows license expired. Renew: microsoft-renew.cc",
    "Apple: Your iCloud storage full. Upgrade: icloud-upgrade.in",
    "Google: Your account compromised. Secure: google-secure.xyz",
    "Windows Defender: Virus detected. Remove: defender-remove.cc",
    "Apple Support: Your iPhone hacked. Fix: iphone-fix.in",
    "Microsoft Office: License suspended. Reactivate: office-reactivate.xyz",
    "Apple ID: Payment failed. Update: appleid-payment.cc",
    "Windows Update: Critical security patch. Install: windows-update.in",
    "Apple Care: Warranty expired. Renew: applecare-renew.xyz",
    "Microsoft 365: Subscription cancelled. Renew: m365-renew.cc",
    "Apple Music: Payment declined. Update: applemusic-payment.in",
    "Windows Firewall: Breach detected. Fix: firewall-fix.xyz",
    "Apple Store: Order verification failed. Verify: applestore-verify.cc",
    "Microsoft Teams: Account locked. Unlock: teams-unlock.in",
    "Apple Pay: Card declined. Add new: applepay-addcard.xyz",
    "Windows 11: Upgrade required. Update: win11-update.cc",
    "Apple TV+: Subscription expired. Renew: appletv-renew.in",
    "Microsoft Azure: Billing issue. Update: azure-billing.xyz",
    "Apple News+: Trial ended. Subscribe: applenews-subscribe.cc",
    "Windows Server: License expired. Renew: winserver-renew.in",
    "Apple Arcade: Subscription cancelled. Renew: arcade-renew.xyz",
    "Microsoft Exchange: Security alert. Verify: exchange-verify.cc",
    "Apple Fitness+: Trial ended. Subscribe: fitness-subscribe.in",
    "Windows Defender ATP: Threat detected. Remove: atp-remove.xyz",
    "Apple Books: Payment failed. Update: applebooks-payment.cc",
    "Microsoft SQL: License expired. Renew: sql-renew.in",
    "Apple Podcasts: Subscription expired. Renew: podcasts-renew.xyz",
    "Windows Hyper-V: Activation failed. Activate: hyperv-activate.cc",
    "Apple Maps: Data corrupted. Fix: maps-fix.in",
    "Microsoft Power BI: Subscription cancelled. Renew: powerbi-renew.xyz",
    "Apple Watch: Sync failed. Fix: watch-sync.cc",
    "Microsoft Dynamics: License expired. Renew: dynamics-renew.in",
    "Apple HomeKit: Device offline. Reconnect: homekit-reconnect.xyz",
    "Windows IoT: Security patch required. Install: iot-patch.cc",
    "Apple AirTag: Lost mode activated. Deactivate: airtag-deactivate.in",
    "Microsoft Visio: License suspended. Reactivate: visio-reactivate.xyz",
    "Apple Pencil: Firmware update failed. Update: pencil-update.cc",
    "Microsoft Project: Subscription expired. Renew: project-renew.in",
    "Apple AirPods: Connection issue. Fix: airpods-fix.xyz",
    "Windows Mixed Reality: Driver outdated. Update: mr-driver.cc",
    "Apple MagSafe: Charging failed. Fix: magsafe-fix.in",
    "Microsoft Access: License expired. Renew: access-renew.xyz",
    "Apple Pro Display: Calibration failed. Calibrate: display-calibrate.cc",
    "Windows Terminal: Profile corrupted. Fix: terminal-fix.in",
    "Apple Silicon: Compatibility issue. Update: silicon-update.xyz",
    "Microsoft Publisher: License suspended. Reactivate: publisher-reactivate.cc",
    "Apple Studio Display: Firmware update. Install: studio-firmware.in",
    "Windows Sandbox: Configuration error. Fix: sandbox-fix.xyz",
    "Apple Magic Keyboard: Pairing failed. Pair: keyboard-pair.cc",
    "Microsoft OneDrive: Storage full. Upgrade: onedrive-upgrade.in",
    
    # Romance/Dating (50)
    "Meet singles in your area! Join: local-singles.xyz",
    "Your dating profile viewed 500 times. Upgrade: dating-upgrade.cc",
    "Match found! Chat now: dating-match.in",
    "Your dating subscription expired. Renew: dating-renew.xyz",
    "Someone sent you a gift! Claim: dating-gift.cc",
    "Premium dating features unlocked. Pay: dating-premium.in",
    "Your dating account verified. Upgrade: dating-verified.xyz",
    "Hot singles waiting! Join: hot-singles.cc",
    "Your dating profile boosted. Pay: dating-boost.in",
    "VIP dating membership. Join: vip-dating.xyz",
    "Your dating photos approved. Upgrade: dating-photos.cc",
    "Exclusive dating events. RSVP: dating-events.in",
    "Your dating matches expired. Renew: dating-matches.xyz",
    "Premium dating algorithm. Upgrade: dating-algorithm.cc",
    "Your dating verification pending. Complete: dating-verify.in",
    "Elite dating circle. Apply: elite-dating.xyz",
    "Your dating subscription upgraded. Pay: dating-upgraded.cc",
    "Dating coach consultation. Book: dating-coach.in",
    "Your dating profile featured. Pay: dating-featured.xyz",
    "International dating. Join: intl-dating.cc",
    "Your dating messages unread. Login: dating-messages.in",
    "Dating success guarantee. Join: dating-guarantee.xyz",
    "Your dating compatibility test. Take: dating-test.cc",
    "Senior dating community. Join: senior-dating.in",
    "Your dating profile incomplete. Complete: dating-incomplete.xyz",
    "Christian dating network. Join: christian-dating.cc",
    "Your dating preferences updated. Confirm: dating-preferences.in",
    "Muslim dating platform. Join: muslim-dating.xyz",
    "Your dating account suspended. Reactivate: dating-suspended.cc",
    "Jewish dating service. Join: jewish-dating.in",
    "Your dating photos rejected. Resubmit: dating-photos-rejected.xyz",
    "LGBTQ+ dating app. Join: lgbtq-dating.cc",
    "Your dating subscription cancelled. Renew: dating-cancelled.in",
    "Professional dating service. Join: pro-dating.xyz",
    "Your dating profile hidden. Unhide: dating-hidden.cc",
    "Speed dating events. Register: speed-dating.in",
    "Your dating account flagged. Verify: dating-flagged.xyz",
    "Blind date matching. Join: blind-date.cc",
    "Your dating messages filtered. Unlock: dating-filtered.in",
    "Long-distance dating. Join: longdistance-dating.xyz",
    "Your dating profile shadowbanned. Appeal: dating-shadowban.cc",
    "Casual dating network. Join: casual-dating.in",
    "Your dating subscription downgraded. Upgrade: dating-downgraded.xyz",
    "Serious relationship dating. Join: serious-dating.cc",
    "Your dating account limited. Verify: dating-limited.in",
    "Marriage-minded dating. Join: marriage-dating.xyz",
    "Your dating profile outdated. Update: dating-outdated.cc",
    "Age-gap dating community. Join: agegap-dating.in",
    "Your dating messages blocked. Unblock: dating-blocked.xyz",
    "Second-chance dating. Join: secondchance-dating.cc",
    
    # Fake Charity (50)
    "Help earthquake victims! Donate: earthquake-donate.xyz",
    "Cancer research fund. Donate: cancer-fund.cc",
    "Orphanage support needed. Donate: orphanage-support.in",
    "Flood relief fund. Donate: flood-relief.xyz",
    "Animal shelter donations. Donate: animal-shelter.cc",
    "Homeless shelter support. Donate: homeless-shelter.in",
    "Disaster relief fund. Donate: disaster-relief.xyz",
    "Children's hospital fund. Donate: children-hospital.cc",
    "Veterans support fund. Donate: veterans-support.in",
    "Food bank donations. Donate: food-bank.xyz",
    "Refugee aid fund. Donate: refugee-aid.cc",
    "Senior citizen support. Donate: senior-support.in",
    "Wildlife conservation. Donate: wildlife-conservation.xyz",
    "Mental health support. Donate: mental-health.cc",
    "Education for all. Donate: education-all.in",
    "Clean water initiative. Donate: clean-water.xyz",
    "Hunger relief fund. Donate: hunger-relief.cc",
    "Disability support fund. Donate: disability-support.in",
    "Environmental protection. Donate: env-protection.xyz",
    "Poverty alleviation. Donate: poverty-alleviation.cc",
    "Women empowerment fund. Donate: women-empowerment.in",
    "Tree planting initiative. Donate: tree-planting.xyz",
    "Medical research fund. Donate: medical-research.cc",
    "Youth development program. Donate: youth-development.in",
    "Ocean cleanup fund. Donate: ocean-cleanup.xyz",
    "Elderly care support. Donate: elderly-care.cc",
    "Rural development fund. Donate: rural-development.in",
    "Air pollution control. Donate: air-pollution.xyz",
    "Child protection fund. Donate: child-protection.cc",
    "Urban development initiative. Donate: urban-development.in",
    "Soil conservation fund. Donate: soil-conservation.xyz",
    "Family support services. Donate: family-support.cc",
    "Renewable energy fund. Donate: renewable-energy.in",
    "Community health program. Donate: community-health.xyz",
    "Biodiversity protection. Donate: biodiversity-cc",
    "Digital literacy fund. Donate: digital-literacy.in",
    "Climate action initiative. Donate: climate-action.xyz",
    "Skill development program. Donate: skill-development.cc",
    "Sustainable agriculture. Donate: sustainable-agri.in",
    "Art and culture fund. Donate: art-culture.xyz",
    "Sports development program. Donate: sports-development.cc",
    "Innovation and research. Donate: innovation-research.in",
    "Heritage preservation fund. Donate: heritage-preservation.xyz",
    "Public safety initiative. Donate: public-safety.cc",
    "Infrastructure development. Donate: infrastructure-dev.in",
    "Social justice fund. Donate: social-justice.xyz",
    "Technology for good. Donate: tech-for-good.cc",
    "Global peace initiative. Donate: global-peace.in",
    "Human rights fund. Donate: human-rights.xyz",
    "Unity and harmony program. Donate: unity-harmony.cc",
]

LEGIT_TEXTS = [
    # Credit Card Statements (30)
    "Dear Customer, your HDFC Bank Credit Card statement for XX is ready. Total amount Rs.35,201 due by 10-FEB.",
    "Dear Customer, your credit card bill of Rs.15,000 is due on 25-Jun. Pay to avoid interest.",
    "Dear Customer, minimum amount due on your card is Rs.1,500. Due date: 20-Jun.",
    "Dear Customer, your total credit card balance is Rs.25,000. Pay by 25-Jun to avoid charges.",
    "Your ICICI Bank credit card statement is ready. Login to view details. -ICICI Bank",
    "SBI Card: Your statement for May 2024 is ready. Total due: Rs.18,500. Due date: 15-Jun.",
    "Axis Bank: Credit card bill generated. Amount: Rs.22,000. Pay by 10-Jul.",
    "Your HDFC Diners Club statement is ready. View at hdfcbank.com.",
    "ICICI Coral Card: Statement ready. Amount due: Rs.8,750. Due: 25-Jun.",
    "Your SBI Card statement is ready. Login to SBI Card app to view.",
    "HDFC: Your credit card EMI of Rs.5,000 is due on 15-Jul.",
    "Axis: Credit card reward points: 12,500 points. Redeem at axisbank.com.",
    "ICICI: Your card limit enhanced to Rs.2,00,000. View details online.",
    "SBI: Cashback of Rs.500 credited to your credit card. Statement: hdfcbank.com.",
    "Your credit card payment of Rs.10,000 received on 15-Jun. Thank you.",
    "HDFC: Your statement is ready. Total: Rs.45,000. Due: 20-Jul.",
    "ICICI: Card statement generated. Amount: Rs.12,000. Due: 25-Jul.",
    "SBI: Credit card bill ready. Total: Rs.8,000. Due: 15-Aug.",
    "Axis: Statement ready. Amount: Rs.15,000. Due: 10-Aug.",
    "HDFC: Your bill is ready. Total: Rs.20,000. Due: 25-Aug.",
    "ICICI: Statement generated. Amount: Rs.18,000. Due: 30-Aug.",
    "SBI: Card bill ready. Total: Rs.22,000. Due: 15-Sep.",
    "Axis: Your statement is ready. Amount: Rs.25,000. Due: 20-Sep.",
    "HDFC: Bill generated. Total: Rs.30,000. Due: 25-Sep.",
    "ICICI: Your statement is ready. Amount: Rs.35,000. Due: 30-Sep.",
    "SBI: Statement ready. Total: Rs.40,000. Due: 15-Oct.",
    "Axis: Bill ready. Amount: Rs.45,000. Due: 20-Oct.",
    "HDFC: Your statement is ready. Total: Rs.50,000. Due: 25-Oct.",
    "ICICI: Statement generated. Amount: Rs.55,000. Due: 30-Oct.",
    "SBI: Your bill is ready. Total: Rs.60,000. Due: 15-Nov.",
    
    # Transaction Alerts (50)
    "A/c XX6844 credited Rs.33,270 on 08-08-2021. Available balance Rs.45,890. -HDFC Bank",
    "Rs.500 debited from A/c XX1234 on 15-06-2024 at AMAZON. Bal Rs.12,500. -SBI",
    "Transaction alert: Rs.1,200 paid to ELECTRICITY BOARD. A/c XX5678. -Axis Bank",
    "Rs.25,000 received in A/c XX9012 from JOHN DOE on 18-06-2024. -HDFC Bank",
    "SBI: Online transaction of Rs.750 successful. Ref: 123456789. Bal Rs.8,250.",
    "Your A/c XX3456 has been debited Rs.2,500 for INSURANCE PREMIUM on 15-06-2024.",
    "Rs.10,000 transferred from A/c XX7890 to A/c XX1234 on 18-06-2024. -ICICI",
    "SBI: Card XX1234 used for Rs.450 at MCDONALDS on 18-06. Bal Rs.5,550.",
    "Rs.5,000 credited to A/c XX5678 via NEFT from ABC CORP on 17-06-2024.",
    "HDFC: UPI payment of Rs.200 to SWIGGY successful. Ref: 987654321.",
    "Axis: Rs.1,500 debited for MOBILE RECHARGE. Bal: Rs.23,500.",
    "ICICI: IMPS credit of Rs.8,000 received. Ref: 456789123.",
    "SBI: ATM withdrawal of Rs.5,000 from MG ROAD branch. Bal: Rs.15,000.",
    "HDFC: EMI of Rs.12,500 debited for HOME LOAN. Next EMI: 05-Aug.",
    "Your A/c XX9999 credited Rs.50,000 via RTGS from XYZ LTD on 19-06-2024.",
    "Axis: Standing instruction of Rs.3,000 executed for MUTUAL FUND SIP.",
    "ICICI: Dividend of Rs.2,500 credited to your account. Ref: DIV2024.",
    "SBI: Interest of Rs.1,200 credited to savings account. Bal: Rs.45,000.",
    "HDFC: Auto-debit of Rs.5,000 for INSURANCE PREMIUM successful.",
    "Your A/c XX7777 debited Rs.8,000 for CREDIT CARD BILL payment.",
    "Axis: NACH debit of Rs.2,000 for LOAN EMI processed successfully.",
    "ICICI: Cash deposit of Rs.15,000 at ATM. Available: Rs.25,000.",
    "SBI: Cheque deposit of Rs.50,000 cleared. Bal: Rs.75,000.",
    "HDFC: Forex card transaction of $100 at NEW YORK. Bal: $900.",
    "Your A/c XX8888 credited Rs.3,000 as CASHBACK for card usage.",
    "Axis: Payment of Rs.4,000 received. Bal: Rs.30,000.",
    "ICICI: Transfer of Rs.6,000 to A/c XX1111. Bal: Rs.20,000.",
    "SBI: Debit of Rs.7,000 for SHOPPING. Bal: Rs.15,000.",
    "HDFC: Credit of Rs.9,000 from SALARY. Bal: Rs.35,000.",
    "Axis: Payment of Rs.10,000 received. Bal: Rs.40,000.",
    "ICICI: Transfer of Rs.11,000 to A/c XX2222. Bal: Rs.25,000.",
    "SBI: Debit of Rs.12,000 for TRAVEL. Bal: Rs.18,000.",
    "HDFC: Credit of Rs.13,000 from REFUND. Bal: Rs.38,000.",
    "Axis: Payment of Rs.14,000 received. Bal: Rs.42,000.",
    "ICICI: Transfer of Rs.15,000 to A/c XX3333. Bal: Rs.28,000.",
    "SBI: Debit of Rs.16,000 for MEDICAL. Bal: Rs.20,000.",
    "HDFC: Credit of Rs.17,000 from BONUS. Bal: Rs.40,000.",
    "Axis: Payment of Rs.18,000 received. Bal: Rs.45,000.",
    "ICICI: Transfer of Rs.19,000 to A/c XX4444. Bal: Rs.30,000.",
    "SBI: Debit of Rs.20,000 for EDUCATION. Bal: Rs.22,000.",
    "HDFC: Credit of Rs.21,000 from INTEREST. Bal: Rs.42,000.",
    "Axis: Payment of Rs.22,000 received. Bal: Rs.48,000.",
    "ICICI: Transfer of Rs.23,000 to A/c XX5555. Bal: Rs.32,000.",
    "SBI: Debit of Rs.24,000 for RENT. Bal: Rs.25,000.",
    "HDFC: Credit of Rs.25,000 from DIVIDEND. Bal: Rs.45,000.",
    "Axis: Payment of Rs.26,000 received. Bal: Rs.50,000.",
    "ICICI: Transfer of Rs.27,000 to A/c XX6666. Bal: Rs.35,000.",
    "SBI: Debit of Rs.28,000 for GROCERIES. Bal: Rs.28,000.",
    "HDFC: Credit of Rs.29,000 from PENSION. Bal: Rs.48,000.",
    "Axis: Payment of Rs.30,000 received. Bal: Rs.52,000.",
    
    # Educational/Security (20)
    "Your ICICI Bank statement is ready. Login to view. Never share OTP. -ICICI Bank",
    "HDFC Bank will never ask for OTP/PIN. Report suspicious calls to 1800-202-6161.",
    "HDFC: Your statement is ready. View at hdfcbank.com. Never share credentials.",
    "SBI Alert: Do not share OTP with anyone. Bank officials never ask for OTP.",
    "ICICI: Beware of phishing calls. Never click on links received via SMS.",
    "Axis Bank: Your OTP for login is 847291. Valid for 10 minutes. Never share.",
    "HDFC: New device login detected. If not you, call 1800-202-6161 immediately.",
    "SBI: Your password will expire in 7 days. Change at onlinesbi.com.",
    "ICICI: Suspicious login attempt blocked. If not you, call 1860-123-4567.",
    "HDFC: Your card has been blocked due to suspicious activity. Call to unblock.",
    "Axis: Security alert. Your card is safe. Never share CVV.",
    "SBI: Fraud alert. We will never ask for your password.",
    "ICICI: Security reminder. Update your password regularly.",
    "HDFC: Alert. Your account is secure. Report suspicious activity.",
    "Axis: Security notice. Your data is protected.",
    "SBI: Alert. Never share your PIN with anyone.",
    "ICICI: Security update. Your account is safe.",
    "HDFC: Alert. We will never call asking for money.",
    "Axis: Security reminder. Keep your card details safe.",
    "SBI: Alert. Report any suspicious SMS to bank.",
    
    # Account/FD/Loan (20)
    "Your FD of Rs.1,00,000 will mature on 30-06-2024. Contact branch for renewal.",
    "Your loan EMI of Rs.15,500 is due on 05-07-2024. Ensure sufficient balance.",
    "Your debit card XX9012 will expire on 30-06-2024. Visit branch for renewal.",
    "Axis Bank: Fixed Deposit of Rs.50,000 matured. Principal + interest credited.",
    "Your savings account XX1111 has been credited with interest of Rs.2,500.",
    "HDFC: Your home loan outstanding is Rs.25,00,000. Next EMI: Rs.22,000 on 10-Jul.",
    "SBI: Your recurring deposit of Rs.5,000/month will mature on 31-Dec-2024.",
    "ICICI: Your car loan EMI of Rs.18,000 is due on 15-Jul. Auto-debit scheduled.",
    "Your account XX2222 minimum balance not maintained. Charges: Rs.500 debited.",
    "Axis: Your salary of Rs.75,000 credited on 01-07-2024. Available: Rs.75,000.",
    "HDFC: Your FD interest of Rs.5,000 credited. Bal: Rs.1,05,000.",
    "SBI: Loan prepayment of Rs.50,000 received. Outstanding: Rs.20,00,000.",
    "ICICI: Your debit card PIN changed successfully.",
    "Axis: FD renewal confirmed. Amount: Rs.60,000. Rate: 7.5%.",
    "HDFC: Your loan EMI paid successfully. Next EMI: 10-Aug.",
    "SBI: Your account upgraded to Premium. Benefits activated.",
    "ICICI: Your FD will mature on 15-Aug. Auto-renewal enabled.",
    "Axis: Loan statement ready. Outstanding: Rs.18,00,000.",
    "HDFC: Your savings account interest credited: Rs.3,000.",
    "SBI: Your debit card delivery scheduled. Track: sbi.co.in.",
    
    # Additional legitimate variations (153)
    "A/c XX1111 credited Rs.1,000 on 01-01-2024. Bal: Rs.11,000. -HDFC",
    "A/c XX2222 credited Rs.2,000 on 02-02-2024. Bal: Rs.22,000. -SBI",
    "A/c XX3333 credited Rs.3,000 on 03-03-2024. Bal: Rs.33,000. -ICICI",
    "A/c XX4444 credited Rs.4,000 on 04-04-2024. Bal: Rs.44,000. -Axis",
    "A/c XX5555 credited Rs.5,000 on 05-05-2024. Bal: Rs.55,000. -HDFC",
    "Rs.1,000 debited from A/c XX1111 on 01-01-2024. Bal: Rs.10,000.",
    "Rs.2,000 debited from A/c XX2222 on 02-02-2024. Bal: Rs.20,000.",
    "Rs.3,000 debited from A/c XX3333 on 03-03-2024. Bal: Rs.30,000.",
    "Rs.4,000 debited from A/c XX4444 on 04-04-2024. Bal: Rs.40,000.",
    "Rs.5,000 debited from A/c XX5555 on 05-05-2024. Bal: Rs.50,000.",
    "UPI payment of Rs.100 to SHOP successful. Ref: 111111.",
    "UPI payment of Rs.200 to STORE successful. Ref: 222222.",
    "UPI payment of Rs.300 to MALL successful. Ref: 333333.",
    "UPI payment of Rs.400 to MARKET successful. Ref: 444444.",
    "UPI payment of Rs.500 to BAZAAR successful. Ref: 555555.",
    "NEFT credit of Rs.10,000 from SENDER1. Ref: NEFT111.",
    "NEFT credit of Rs.20,000 from SENDER2. Ref: NEFT222.",
    "NEFT credit of Rs.30,000 from SENDER3. Ref: NEFT323.",
    "NEFT credit of Rs.40,000 from SENDER4. Ref: NEFT444.",
    "NEFT credit of Rs.50,000 from SENDER5. Ref: NEFT555.",
    "IMPS transfer of Rs.5,000 to RECEIVER1 successful.",
    "IMPS transfer of Rs.6,000 to RECEIVER2 successful.",
    "IMPS transfer of Rs.7,000 to RECEIVER3 successful.",
    "IMPS transfer of Rs.8,000 to RECEIVER4 successful.",
    "IMPS transfer of Rs.9,000 to RECEIVER5 successful.",
    "RTGS credit of Rs.1,00,000 from COMPANY1. Ref: RTGS111.",
    "RTGS credit of Rs.2,00,000 from COMPANY2. Ref: RTGS222.",
    "RTGS credit of Rs.3,00,000 from COMPANY3. Ref: RTGS333.",
    "RTGS credit of Rs.4,00,000 from COMPANY4. Ref: RTGS444.",
    "RTGS credit of Rs.5,00,000 from COMPANY5. Ref: RTGS555.",
    "ATM withdrawal of Rs.2,000 from BRANCH1. Bal: Rs.20,000.",
    "ATM withdrawal of Rs.3,000 from BRANCH2. Bal: Rs.30,000.",
    "ATM withdrawal of Rs.4,000 from BRANCH3. Bal: Rs.40,000.",
    "ATM withdrawal of Rs.5,000 from BRANCH4. Bal: Rs.50,000.",
    "ATM withdrawal of Rs.6,000 from BRANCH5. Bal: Rs.60,000.",
    "Your statement for Jan 2024 is ready. Total: Rs.10,000.",
    "Your statement for Feb 2024 is ready. Total: Rs.20,000.",
    "Your statement for Mar 2024 is ready. Total: Rs.30,000.",
    "Your statement for Apr 2024 is ready. Total: Rs.40,000.",
    "Your statement for May 2024 is ready. Total: Rs.50,000.",
    "Your statement for Jun 2024 is ready. Total: Rs.60,000.",
    "Your statement for Jul 2024 is ready. Total: Rs.70,000.",
    "Your statement for Aug 2024 is ready. Total: Rs.80,000.",
    "Your statement for Sep 2024 is ready. Total: Rs.90,000.",
    "Your statement for Oct 2024 is ready. Total: Rs.1,00,000.",
    "Your statement for Nov 2024 is ready. Total: Rs.1,10,000.",
    "Your statement for Dec 2024 is ready. Total: Rs.1,20,000.",
    "Credit card statement: Total Rs.15,000. Min due: Rs.1,500.",
    "Credit card statement: Total Rs.25,000. Min due: Rs.2,500.",
    "Credit card statement: Total Rs.35,000. Min due: Rs.3,500.",
    "Credit card statement: Total Rs.45,000. Min due: Rs.4,500.",
    "Credit card statement: Total Rs.55,000. Min due: Rs.5,500.",
    "Your credit card bill of Rs.20,000 is due on 15-Jan.",
    "Your credit card bill of Rs.30,000 is due on 15-Feb.",
    "Your credit card bill of Rs.40,000 is due on 15-Mar.",
    "Your credit card bill of Rs.50,000 is due on 15-Apr.",
    "Your credit card bill of Rs.60,000 is due on 15-May.",
    "Your home loan EMI of Rs.25,000 is due on 10-Jan.",
    "Your home loan EMI of Rs.30,000 is due on 10-Feb.",
    "Your home loan EMI of Rs.35,000 is due on 10-Mar.",
    "Your home loan EMI of Rs.40,000 is due on 10-Apr.",
    "Your home loan EMI of Rs.45,000 is due on 10-May.",
    "Your car loan EMI of Rs.15,000 is due on 5-Jan.",
    "Your car loan EMI of Rs.20,000 is due on 5-Feb.",
    "Your car loan EMI of Rs.25,000 is due on 5-Mar.",
    "Your car loan EMI of Rs.30,000 is due on 5-Apr.",
    "Your car loan EMI of Rs.35,000 is due on 5-May.",
    "Your personal loan EMI of Rs.10,000 is due on 1-Jan.",
    "Your personal loan EMI of Rs.15,000 is due on 1-Feb.",
    "Your personal loan EMI of Rs.20,000 is due on 1-Mar.",
    "Your personal loan EMI of Rs.25,000 is due on 1-Apr.",
    "Your personal loan EMI of Rs.30,000 is due on 1-May.",
    "Education loan EMI of Rs.8,000 is due on 20-Jan.",
    "Education loan EMI of Rs.10,000 is due on 20-Feb.",
    "Education loan EMI of Rs.12,000 is due on 20-Mar.",
    "Education loan EMI of Rs.14,000 is due on 20-Apr.",
    "Education loan EMI of Rs.16,000 is due on 20-May.",
    "Your FD of Rs.1,00,000 matured on 01-Jan-2024. Principal + interest credited.",
    "Your FD of Rs.2,00,000 matured on 01-Feb-2024. Principal + interest credited.",
    "Your FD of Rs.3,00,000 matured on 01-Mar-2024. Principal + interest credited.",
    "Your FD of Rs.4,00,000 matured on 01-Apr-2024. Principal + interest credited.",
    "Your FD of Rs.5,00,000 matured on 01-May-2024. Principal + interest credited.",
    "RD of Rs.5,000/month matured on 15-Jan-2024. Total: Rs.65,000 credited.",
    "RD of Rs.10,000/month matured on 15-Feb-2024. Total: Rs.1,30,000 credited.",
    "RD of Rs.15,000/month matured on 15-Mar-2024. Total: Rs.1,95,000 credited.",
    "RD of Rs.20,000/month matured on 15-Apr-2024. Total: Rs.2,60,000 credited.",
    "RD of Rs.25,000/month matured on 15-May-2024. Total: Rs.3,25,000 credited.",
    "HDFC Bank: Never share your CVV, PIN, or OTP with anyone.",
    "SBI: Bank officials will never call asking for your password.",
    "ICICI: Report any suspicious calls to 1800-123-4567.",
    "Axis: Keep your card details safe. Never share with anyone.",
    "Federal: Beware of phishing emails. Always verify sender.",
    "Kotak: Your account is secure. Report suspicious activity.",
    "Yes Bank: Never click on links in unsolicited emails.",
    "IndusInd: Update your password regularly for security.",
    "IDFC First: Enable two-factor authentication for extra security.",
    "RBL Bank: Monitor your account statements regularly.",
    "Bank of Baroda: Never share OTP with anyone, even bank staff.",
    "PNB: Be cautious of calls asking for personal information.",
    "Canara Bank: Verify the authenticity of emails before clicking links.",
    "Union Bank: Use strong passwords and change them periodically.",
    "Indian Bank: Enable transaction alerts for all your accounts.",
    "Your credit card reward points: 15,000. Redeem at hdfcbank.com.",
    "Your credit card reward points: 20,000. Redeem at sbicard.com.",
    "Your credit card reward points: 25,000. Redeem at icicibank.com.",
    "Your credit card reward points: 30,000. Redeem at axisbank.com.",
    "Your credit card reward points: 35,000. Redeem at federalbank.com.",
    "Your debit card will expire on 31-Dec-2024. Visit branch for renewal.",
    "Your debit card will expire on 31-Jan-2025. Visit branch for renewal.",
    "Your debit card will expire on 28-Feb-2025. Visit branch for renewal.",
    "Your debit card will expire on 31-Mar-2025. Visit branch for renewal.",
    "Your debit card will expire on 30-Apr-2025. Visit branch for renewal.",
    "Your netbanking password will expire in 30 days. Change at bank website.",
    "Your netbanking password will expire in 25 days. Change at bank website.",
    "Your netbanking password will expire in 20 days. Change at bank website.",
    "Your netbanking password will expire in 15 days. Change at bank website.",
    "Your netbanking password will expire in 10 days. Change at bank website.",
    "Your account has been upgraded to Premium. Enjoy exclusive benefits.",
    "Your account has been upgraded to Gold. Enjoy exclusive benefits.",
    "Your account has been upgraded to Platinum. Enjoy exclusive benefits.",
    "Your account has been upgraded to Diamond. Enjoy exclusive benefits.",
    "Your account has been upgraded to Elite. Enjoy exclusive benefits.",
    "Your cheque book of 25 leaves dispatched. Track: bank website.",
    "Your cheque book of 50 leaves dispatched. Track: bank website.",
    "Your cheque book of 100 leaves dispatched. Track: bank website.",
    "Your new debit card dispatched. Delivery in 5-7 days.",
    "Your replacement debit card dispatched. Delivery in 5-7 days.",
    "Your credit card dispatched. Delivery in 7-10 days.",
    "Your replacement credit card dispatched. Delivery in 7-10 days.",
    "Your welcome kit dispatched. Delivery in 10-15 days.",
    "Your passbook dispatched. Delivery in 5-7 days.",
    "Your account statement dispatched. Delivery in 3-5 days.",
    "Your TDS certificate is ready for download. Login to view.",
    "Your Form 16 is ready for download. Login to view.",
    "Your interest certificate is ready for download. Login to view.",
    "Your capital gains statement is ready. Login to view.",
    "Your annual account statement is ready. Login to view.",
    "Your locker rent of Rs.2,000 debited on 01-Jan-2024.",
    "Your locker rent of Rs.3,000 debited on 01-Feb-2024.",
    "Your locker rent of Rs.4,000 debited on 01-Mar-2024.",
    "Your locker rent of Rs.5,000 debited on 01-Apr-2024.",
    "Your locker rent of Rs.6,000 debited on 01-May-2024.",
    "Your SMS alert charges of Rs.15 debited on 01-Jan-2024.",
    "Your SMS alert charges of Rs.15 debited on 01-Feb-2024.",
    "Your SMS alert charges of Rs.15 debited on 01-Mar-2024.",
    "Your SMS alert charges of Rs.15 debited on 01-Apr-2024.",
    "Your SMS alert charges of Rs.15 debited on 01-May-2024.",
    "Your annual maintenance charge of Rs.500 debited on 01-Jan-2024.",
    "Your annual maintenance charge of Rs.500 debited on 01-Jul-2024.",
    "Your debit card annual fee of Rs.250 debited on 01-Jan-2024.",
    "Your debit card annual fee of Rs.250 debited on 01-Jul-2024.",
    "Your credit card annual fee of Rs.1,000 debited on 01-Jan-2024.",
    "Your credit card annual fee of Rs.1,000 debited on 01-Jul-2024.",
]

# =====================================================================
# MAIN TRAINING FUNCTION
# =====================================================================
def main():
    print("=" * 70)
    print("TRAINING PRIMARY STATISTICAL ML MODEL")
    print("=" * 70)
    print()
    
    # Combine data
    texts = SCAM_TEXTS + LEGIT_TEXTS
    labels = [1] * len(SCAM_TEXTS) + [0] * len(LEGIT_TEXTS)
    
    print(f"Training data: {len(SCAM_TEXTS)} scams + {len(LEGIT_TEXTS)} legitimate = {len(texts)} total")
    print()
    
    # Create pipeline: TF-IDF + Statistical Features → Gradient Boosting
    print("Creating feature extraction pipeline...")
    
    # TF-IDF for text patterns (n-grams capture word combinations)
    tfidf = TfidfVectorizer(
        max_features=1000,
        ngram_range=(1, 3),  # unigrams, bigrams, trigrams
        stop_words='english',
        sublinear_tf=True,
        min_df=2
    )
    
    # Statistical features (imported from feature_extractor.py)
    stat_extractor = StatisticalFeatureExtractor()
    
    # Combine features
    feature_union = FeatureUnion([
        ('tfidf', tfidf),
        ('stats', stat_extractor)
    ])
    
    # Full pipeline
    pipeline = Pipeline([
        ('features', feature_union),
        ('clf', GradientBoostingClassifier(
            n_estimators=300,
            max_depth=6,
            learning_rate=0.1,
            random_state=42,
            min_samples_split=5,
            min_samples_leaf=2,
            subsample=0.8
        ))
    ])
    
    # Cross-validation
    print("Running 5-fold cross-validation...")
    cv_scores = cross_val_score(pipeline, texts, labels, cv=5, scoring='accuracy')
    print(f"Cross-validation accuracy: {cv_scores.mean():.2%} (±{cv_scores.std():.2%})")
    print()
    
    # Train on full dataset
    print("Training final model...")
    pipeline.fit(texts, labels)
    
    # Save the model
    model_path = MODEL_DIR / "primary_statistical_model.pkl"
    with open(model_path, 'wb') as f:
        pickle.dump(pipeline, f)
    
    print(f"✓ Model saved to: {model_path}")
    print()
    
    print("=" * 70)
    print("TRAINING COMPLETE")
    print("=" * 70)
    print()
    print("This model is now the PRIMARY detector.")
    print("It uses TF-IDF n-grams + statistical features.")
    print("NO hardcoded patterns - purely learned from data!")
    print()
    print("Next: Update backend/main.py to use this as PRIMARY detector")
    print("=" * 70)

if __name__ == "__main__":
    main()